// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNN9QH7NhQFdc0Avp9yklMSYYv27nUAs',
    appId: '1:686756139829:web:aee30fe61f9141b6d1f27c',
    messagingSenderId: '686756139829',
    projectId: 'warm-physics-470205-e0',
    authDomain: 'warm-physics-470205-e0.firebaseapp.com',
    storageBucket: 'warm-physics-470205-e0.firebasestorage.app',
    measurementId: 'G-4Y7VPM2ZB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDplyoJAfRH8eWvtHivkwMG6C8vnX1Fc4g',
    appId: '1:686756139829:android:09707291c85a8d46d1f27c',
    messagingSenderId: '686756139829',
    projectId: 'warm-physics-470205-e0',
    storageBucket: 'warm-physics-470205-e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV-iOQDJ4hS2EVicbisdRE7PNW_xVRu3Q',
    appId: '1:686756139829:ios:a6b5cfd470ca7de0d1f27c',
    messagingSenderId: '686756139829',
    projectId: 'warm-physics-470205-e0',
    storageBucket: 'warm-physics-470205-e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV-iOQDJ4hS2EVicbisdRE7PNW_xVRu3Q',
    appId: '1:686756139829:ios:a6b5cfd470ca7de0d1f27c',
    messagingSenderId: '686756139829',
    projectId: 'warm-physics-470205-e0',
    storageBucket: 'warm-physics-470205-e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoNN9QH7NhQFdc0Avp9yklMSYYv27nUAs',
    appId: '1:686756139829:web:aee30fe61f9141b6d1f27c',
    messagingSenderId: '686756139829',
    projectId: 'warm-physics-470205-e0',
    authDomain: 'warm-physics-470205-e0.firebaseapp.com',
    storageBucket: 'warm-physics-470205-e0.firebasestorage.app',
    measurementId: 'G-4Y7VPM2ZB1',
  );
}
